Repository stoplightio/elements, pull requests merged in 2021-05, with the labels that each got.

#1156 chore: demo -> elements dependency
  demo/package.json
  yarn.lock
Labels: team/undefined

#1154 chore: remove mentions of StoplightProject from elements
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements/src/components/Docs/HttpOperation/HttpOperation.tsx
  packages/elements/src/components/Docs/HttpService/HttpService.tsx
  packages/elements/src/components/Docs/HttpService/ServerInfo.tsx
  packages/elements/src/components/Docs/HttpService/__tests__/index.spec.tsx
  packages/elements/src/containers/Docs.tsx
  packages/elements/src/containers/Provider.tsx
  packages/elements/src/types.ts
Labels: team/undefined

#1146 feat: add "Powered by Stoplight" branding
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements/src/components/API/SidebarLayout.tsx
  packages/elements/src/components/Docs/HttpService/HttpService.tsx
  packages/elements/src/components/PoweredByLink.tsx
Labels: team/undefined

#1166 fix(schema-and-description): do not pass default title & description
  packages/elements/src/components/SchemaAndDescription/SchemaAndDescription.spec.tsx
  packages/elements/src/components/SchemaAndDescription/index.tsx
Labels: bug

#1152 fix: icons missing in angular example
  examples/angular/yarn.lock
  packages/elements/src/components/MosaicTableOfContents/TableOfContents.tsx
  packages/elements/src/components/MosaicTableOfContents/constants.ts
Labels: team/undefined

#1168 fix: clickable security badges
  packages/elements/src/utils/oas/__tests__/security.spec.ts
  packages/elements/src/utils/oas/security.ts
Labels: team/undefined

#1170 test: increase timeout to prevent errors
  packages/elements/jest.config.js
Labels: team/undefined

#1161 feat: use Menu instead of Select for RequestSamples
  cypress/integration/api.ts
  cypress/integration/stoplight-project.ts
  packages/elements/src/components/RequestSamples/RequestSamples.tsx
  packages/elements/src/components/RequestSamples/__tests__/RequestSamples.test.tsx
  packages/elements/src/components/RequestSamples/requestSampleConfigs.ts
Labels: team/undefined

#1215 chore: examples location
  examples/angular/src/app/stoplight-project/stoplight-project.component.ts
  examples/react-cra/README.md
  examples/react-cra/src/components/StoplightProject.tsx
  examples/react-gatsby/src/pages/stoplight-project-demo.tsx
  packages/elements-core/src/components/Docs/HttpService/__tests__/index.spec.tsx
  packages/elements-core/src/containers/TableOfContents.stories.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.stories.tsx
Labels: team/undefined

#1191 feat(dev-portal): node content component
  packages/elements-core/src/components/MosaicTableOfContents/types.ts
  packages/elements-dev-portal/.storybook/preview.jsx
  packages/elements-dev-portal/package.json
  packages/elements-dev-portal/src/components/DevPortalProvider/index.tsx
  packages/elements-dev-portal/src/components/NodeContent/NodeContent.stories.tsx
  packages/elements-dev-portal/src/components/NodeContent/index.tsx
  packages/elements-dev-portal/src/handlers/getNodeContent.ts
  packages/elements-dev-portal/src/hooks/useGetNodeContent.ts
  packages/elements-dev-portal/src/index.ts
  packages/elements-dev-portal/src/types.ts
Labels: commit/2021-05-11, team/undefined

#1202 Feat: x-logo support
  packages/elements-core/src/components/Logo.tsx
  packages/elements/jest.config.js
  packages/elements/src/__fixtures__/api-descriptions/Instagram.ts
  packages/elements/src/components/API/APIWithSidebarLayout.tsx
  packages/elements/src/containers/API.spec.tsx
  packages/elements/src/containers/API.tsx
Labels: team/undefined

#1213 chore: weekly maintenance v2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: team/undefined

#1177 chore: upgrade gatsby example to 3.x
  examples/react-gatsby/gatsby-config.js
  examples/react-gatsby/gatsby-node.js
  examples/react-gatsby/package.json
  examples/react-gatsby/yarn.lock
Labels: commit/2021-05-11

#1235 chore: don't include scope
  .github/dependabot.yml
Labels: team/undefined

#1193 feat(dev-portal): branch selector
  packages/elements-dev-portal/.storybook/preview-head.html
  packages/elements-dev-portal/src/components/BranchSelector/BranchSelector.stories.tsx
  packages/elements-dev-portal/src/components/BranchSelector/index.tsx
  packages/elements-dev-portal/src/handlers/getBranches.ts
  packages/elements-dev-portal/src/hooks/useGetBranches.ts
  packages/elements-dev-portal/src/index.ts
  packages/elements-dev-portal/src/types.ts
Labels: commit/2021-05-11, team/undefined

#1253 fix: building styles
  README.md
  docs/guides/angular.md
  docs/guides/react.md
  examples/angular/angular.json
  examples/bootstrap/index.html
  examples/react-cra/src/components/API.tsx
  examples/react-cra/src/components/StoplightProject.tsx
  examples/react-gatsby/src/components/layout.tsx
  packages/elements-core/.storybook/preview.jsx
  packages/elements-core/package.json
  packages/elements-core/src/styles/styles.scss
  packages/elements-dev-portal/.storybook/preview.jsx
  packages/elements-dev-portal/package.json
  packages/elements/.storybook/preview.jsx
  packages/elements/package.json
  scripts/build-styles.js
Labels: team/undefined

#1262 Fix: Server URL path is removed when sending request
  package.json
  packages/elements-core/src/__fixtures__/operations/with-url-variables.ts
  packages/elements-core/src/components/TryIt/TryIt.spec.tsx
  packages/elements-core/src/components/TryIt/build-request.ts
Labels: bug, team/undefined

#1194 feat(dev-portal): search component
  demo/package.json
  packages/elements-core/package.json
  packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
  packages/elements-core/src/components/Docs/Sections.tsx
  packages/elements-dev-portal/package.json
  packages/elements-dev-portal/src/components/Search/Search.stories.tsx
  packages/elements-dev-portal/src/components/Search/index.tsx
  packages/elements-dev-portal/src/handlers/getNodes.ts
  packages/elements-dev-portal/src/hooks/useGetNodes.ts
  packages/elements-dev-portal/src/index.ts
  packages/elements-dev-portal/src/types.ts
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1195 feat(dev-portal): stoplight project component
  cypress/integration/stoplight-project.ts
  examples/angular/src/app/stoplight-project/stoplight-project.component.html
  examples/angular/src/app/stoplight-project/stoplight-project.component.ts
  examples/react-cra/src/components/StoplightProject.tsx
  examples/react-gatsby/src/pages/stoplight-project-demo.tsx
  packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
  packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
  packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
  packages/elements-core/src/components/MosaicTableOfContents/types.ts
  packages/elements-core/src/components/MosaicTableOfContents/utils.ts
  packages/elements-core/src/components/TryIt/mocking-utils.ts
  packages/elements-core/src/containers/Docs.tsx
  packages/elements-core/src/containers/Provider.tsx
  packages/elements-dev-portal/package.json
  packages/elements-dev-portal/src/components/BranchSelector/BranchSelector.stories.tsx
  packages/elements-dev-portal/src/components/Loading/index.tsx
  packages/elements-dev-portal/src/components/NodeContent/NodeContent.stories.tsx
  packages/elements-dev-portal/src/components/NodeContent/index.tsx
  packages/elements-dev-portal/src/components/NotFound/index.tsx
  packages/elements-dev-portal/src/components/Search/Search.stories.tsx
  packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.stories.tsx
  packages/elements-dev-portal/src/components/TableOfContents/index.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.stories.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements-dev-portal/src/handlers/getBranches.ts
  packages/elements-dev-portal/src/handlers/getNodeContent.ts
  packages/elements-dev-portal/src/handlers/getNodes.ts
  packages/elements-dev-portal/src/handlers/getTableOfContents.ts
  packages/elements-dev-portal/src/hooks/useGetBranches.ts
  packages/elements-dev-portal/src/hooks/useGetNodeContent.ts
  packages/elements-dev-portal/src/hooks/useGetTableOfContents.ts
  packages/elements-dev-portal/src/web-components/__stories__/StoplightProject.stories.tsx
  packages/elements-dev-portal/src/web-components/components.ts
  packages/elements-dev-portal/tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: commit/2021-05-11, team/undefined

#1293 Feat/display upgrade workspace screen
  packages/elements-dev-portal/src/components/UpgradeToStarter/index.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements-dev-portal/src/handlers/getNodeContent.ts
Labels: team/undefined

#1297 Fix: basePath missing in request samples
  packages/elements-core/src/components/TryIt/TryItWithRequestSamples.spec.tsx
  packages/elements-core/src/components/TryIt/build-request.ts
Labels: team/undefined

#1295 feat(demo): add CORS proxy functionality
  demo/src/components/ElementsAPI.tsx
  package.json
Labels: team/undefined

#1300 feat: dev-portal beta 1
  demo/package.json
  packages/elements-core/package.json
  packages/elements-dev-portal/package.json
  packages/elements-utils/package.json
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1284 feat(elements-core): index export
  packages/elements-core/package.json
  packages/elements-core/src/components/Docs/Model/Model.tsx
  packages/elements-core/src/hooks/useParsedData.ts
  packages/elements-core/src/index.ts
  packages/elements-core/src/types.ts
  packages/elements-core/src/utils/guards.ts
  packages/elements-dev-portal/.storybook/preview.jsx
  packages/elements-dev-portal/src/components/DevPortalProvider/index.tsx
  packages/elements-dev-portal/src/components/NodeContent/index.tsx
  packages/elements-dev-portal/src/components/Search/index.tsx
  packages/elements-dev-portal/src/components/TableOfContents/index.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements-dev-portal/src/types.ts
  packages/elements/.storybook/preview.jsx
  packages/elements/jest.config.js
  packages/elements/package.json
  packages/elements/src/components/API/APIWithSidebarLayout.tsx
  packages/elements/src/components/API/APIWithStackedLayout.tsx
  packages/elements/src/components/API/utils.ts
  packages/elements/src/containers/API.tsx
  packages/elements/src/utils/oas/types.ts
  yarn.lock
Labels: team/undefined

#1309 feat: add scss to core build
  packages/elements-core/package.json
  scripts/build-styles.js
Labels: team/undefined

#1307 chore: dead code purge
  packages/elements-core/jest.config.js
  packages/elements-core/package.json
  packages/elements-core/src/components/Content/index.tsx
  packages/elements-core/src/components/Docs/Article/index.tsx
  packages/elements-core/src/components/Docs/HttpOperation/Method.tsx
  packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx
  packages/elements-core/src/components/Docs/HttpOperation/Path.tsx
  packages/elements-core/src/components/Docs/HttpOperation/Request.tsx
  packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
  packages/elements-core/src/components/Docs/HttpOperation/utils.ts
  packages/elements-core/src/components/Docs/HttpSecuritySchemes/index.tsx
  packages/elements-core/src/components/Docs/HttpService/SecuritySchemes.tsx
  packages/elements-core/src/components/RequestSamples/requestSampleConfigs.ts
  packages/elements-core/src/components/SchemaAndDescription/index.tsx
  packages/elements-core/src/components/Search/List.tsx
  packages/elements-core/src/components/Search/SearchBar.tsx
  packages/elements-core/src/components/Search/__tests__/index.spec.tsx
  packages/elements-core/src/components/Search/index.tsx
  packages/elements-core/src/components/TableOfContents/Row.tsx
  packages/elements-core/src/hooks/useDereferencedHttpOperation.spec.ts
  packages/elements-core/src/hooks/useDereferencedHttpOperation.ts
  packages/elements-core/src/index.ts
  packages/elements-core/src/styles/_HttpOperation.scss
  packages/elements-core/src/styles/_Page.scss
  packages/elements-core/src/styles/_Search.scss
  packages/elements-core/src/styles/_TryIt.scss
  packages/elements-core/src/styles/_main.scss
  packages/elements-core/src/styles/elements.scss
  packages/elements-core/src/types.ts
  packages/elements-core/src/utils/arrayBuffer.ts
  packages/elements-core/src/utils/guards.ts
  packages/elements-core/src/utils/highlightText.tsx
  packages/elements-core/src/utils/prettifiers/json.ts
  packages/elements-core/src/utils/prettifiers/types.ts
  packages/elements-core/src/utils/stringifiers/html.ts
  packages/elements-core/src/utils/stringifiers/types.ts
  packages/elements-core/src/utils/stringifiers/xml.ts
  packages/elements-core/tsconfig.build.json
  packages/elements-dev-portal/package.json
  packages/elements-utils/src/index.ts
  packages/elements-utils/src/toc/__tests__/__snapshots__/toc.test.ts.snap
  packages/elements-utils/src/toc/__tests__/toc.test.ts
  packages/elements-utils/src/toc/toc.ts
  packages/elements/jest.config.js
  packages/elements/package.json
  packages/elements/tsconfig.build.json
  yarn.lock
Labels: team/undefined

#1259 chore: perform builds concurrently
  package.json
  packages/elements-dev-portal/package.json
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1324 fix: flaky e2e api tests
  .gitignore
  cypress/integration/api.ts
  examples/react-gatsby/yarn.lock
  yarn.lock
Labels: team/undefined

#1327 chore(angular): angular 12
  examples/angular/package.json
  examples/angular/yarn.lock
Labels: team/undefined

#1329 feat(Docs): Markdown support in Parameters descriptions
  packages/elements-core/package.json
  packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx
  packages/elements-core/src/styles/_HttpOperation.scss
  yarn.lock
Labels: team/undefined

#1328 feat(docs): model titles
  packages/elements-core/src/__fixtures__/articles/kitchen-sink.md
  packages/elements-core/src/components/Docs/Docs.tsx
  packages/elements-core/src/components/Docs/Model/Model.tsx
  packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
  packages/elements-core/src/components/SchemaAndDescription/SchemaAndDescription.spec.tsx
  packages/elements-core/src/components/SchemaAndDescription/index.tsx
  packages/elements-dev-portal/src/components/NodeContent/index.tsx
  packages/elements/src/components/API/APIWithSidebarLayout.tsx
  packages/elements/src/components/API/APIWithStackedLayout.tsx
Labels: team/undefined

#1331 fix: automated release
  .circleci/config.yml
  demo/package.json
  package.json
  packages/elements-core/package.json
  packages/elements-dev-portal/package.json
  packages/elements/package.json
  yarn.lock
Labels: team/undefined
