Repository stoplightio/elements, pull requests merged in 2021-04, with the labels that each got.

#1036 fix: wrap parameter descriptions
  packages/elements/src/components/Docs/HttpOperation/Parameters.tsx
  packages/elements/src/containers/API.stories.tsx
Labels: bug, team/undefined

#1040 Fix(toc): missing caret icon in web components
  packages/elements-web-components/package.json
  packages/elements-web-components/src/index.ts
Labels: team/undefined

#1080 fix(docs): scroll to top
  packages/elements/src/components/API/SidebarLayout.tsx
  packages/elements/src/components/TableOfContents/Row.tsx
Labels: team/undefined

#1104 fix: unknown pathname
  packages/elements/src/components/API/SidebarLayout.tsx
Labels: team/undefined

#1090 feat: set up CI workflow for lockfile maintenance
  .circleci/config.yml
Labels: team/undefined

#1115 chore: remove Renovate config file
  renovate.json
Labels: team/undefined

#1106 chore(storybook): bump version
  demo/package.json
  package.json
  packages/elements/package.json
  packages/elements/src/web-components/__stories__/StoplightProject.stories.tsx
  yarn.lock
Labels: team/undefined

#1112 fix: root level jsv display
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1121 release: 7.0.0-beta.1
  demo/package.json
  examples/angular/package.json
  examples/angular/yarn.lock
  lerna.json
  packages/elements-utils/package.json
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1122 chore: lockfile maintenance
  demo/package.json
  packages/elements/package.json
  packages/elements/src/components/Docs/HttpOperation/Body.tsx
  packages/elements/src/components/Docs/HttpOperation/Responses.tsx
  packages/elements/src/components/Docs/HttpSecuritySchemes/index.tsx
  packages/elements/src/components/RequestSamples/RequestSamples.tsx
  packages/elements/src/components/ResponseExamples/ResponseExamples.tsx
  packages/elements/src/components/TryIt/FormDataBody.tsx
  packages/elements/src/components/TryIt/OperationParameters.tsx
  packages/elements/src/constants.ts
  packages/elements/src/utils/oas/security.ts
  yarn.lock
Labels: team/undefined

#1123 chore: add API sidebar layout story to Storybook
  packages/elements/src/containers/API.stories.tsx
Labels: team/undefined

#1109 chore: better typings after transforming oas file
  packages/elements/package.json
  packages/elements/src/components/API/SidebarLayout.tsx
  packages/elements/src/components/API/StackedLayout.tsx
  packages/elements/src/components/API/__tests__/utils.test.ts
  packages/elements/src/components/API/utils.ts
  packages/elements/src/constants.ts
  packages/elements/src/containers/API.tsx
  packages/elements/src/containers/__tests__/API.test.ts
  packages/elements/src/utils/oas/__tests__/oas.spec.ts
  packages/elements/src/utils/oas/index.ts
  packages/elements/src/utils/oas/oas2.ts
  packages/elements/src/utils/oas/oas3.ts
  packages/elements/src/utils/oas/security.ts
  packages/elements/src/utils/oas/types.ts
Labels: team/undefined

#1118 chore: remove SASS svg function from storybook
  packages/elements/.storybook/main.js
  packages/elements/package.json
  yarn.lock
Labels: team/undefined

#1139 fix: select dropdown
  cypress/integration/api.ts
  cypress/integration/stoplight-project.ts
  packages/elements/src/containers/API.tsx
Labels: team/undefined

#1134 feat: Embed TryIt in Articles
  packages/elements/src/components/MarkdownViewer/CustomComponents/CodeComponent.spec.ts
  packages/elements/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
  packages/elements/src/components/MarkdownViewer/CustomComponents/CodeWithSchemaViewer.tsx
  packages/elements/src/components/MarkdownViewer/CustomComponents/Provider.tsx
  packages/elements/src/components/MarkdownViewer/MarkdownViewer.spec.tsx
Labels: team/undefined

#1143 feat: add preliminary support for OAS 3.1
  packages/elements-utils/package.json
  packages/elements-web-components/package.json
  packages/elements/package.json
  packages/elements/src/components/Docs/HttpOperation/Parameters.tsx
  packages/elements/src/components/RequestMaker/Request/Mocking.tsx
  packages/elements/src/components/RequestMaker/__tests__/RequestMocking.spec.tsx
  packages/elements/src/components/SchemaViewer/index.tsx
  packages/elements/src/constants.ts
  packages/elements/src/context/InlineRefResolver.tsx
  packages/elements/src/stores/request-maker/__tests__/index.spec.ts
  packages/elements/src/stores/request-maker/index.ts
  packages/elements/src/utils/getOperationData.ts
  packages/elements/src/utils/guards.ts
  yarn.lock
Labels: enhancement

#1145 chore: set 6.2.1 versions in package.json
  CHANGELOG.md
  lerna.json
  packages/elements-utils/CHANGELOG.md
  packages/elements-utils/package.json
  packages/elements-web-components/CHANGELOG.md
  packages/elements-web-components/package.json
  packages/elements/CHANGELOG.md
  packages/elements/package.json
Labels: chore

#1110 feat(API): new TableOfContents using Mosaic
  cypress/integration/api.ts
  demo/package.json
  packages/elements/.storybook/preview-head.html
  packages/elements/package.json
  packages/elements/src/components/API/SidebarLayout.tsx
  packages/elements/src/components/API/utils.ts
  packages/elements/src/components/MosaicTableOfContents/TableOfContents.spec.tsx
  packages/elements/src/components/MosaicTableOfContents/TableOfContents.stories.tsx
  packages/elements/src/components/MosaicTableOfContents/TableOfContents.tsx
  packages/elements/src/components/MosaicTableOfContents/constants.ts
  packages/elements/src/components/MosaicTableOfContents/index.ts
  packages/elements/src/components/MosaicTableOfContents/types.ts
  packages/elements/src/components/MosaicTableOfContents/utils.ts
  packages/elements/src/styles/elements.scss
  yarn.lock
Labels: commit/2021-04-27, team/undefined

#1147 fix(TableOfContents): use operationId before path
  packages/elements/src/utils/oas/__tests__/oas.spec.ts
  packages/elements/src/utils/oas/index.ts
Labels: team/undefined

#1144 Chore: independent package versioning
  .circleci/config.yml
  lerna.json
  package.json
Labels: team/undefined

#1151 fix: incorrect lerna command in CirlcleCI job
  .circleci/config.yml
Labels: team/undefined

#1153 fix: make elements-dev-portal private
  packages/elements-dev-portal/package.json
Labels: team/undefined

#1150 feat: add styles to elements-dev-portal
  examples/angular/angular.json
  packages/elements-dev-portal/.storybook/preview.jsx
  packages/elements-dev-portal/package.json
  packages/elements-dev-portal/src/styles/elements-dev-portal-scoped.scss
  packages/elements/package.json
  packages/elements/src/styles/_API.scss
  scripts/build-styles.js
Labels: team/undefined
