Repository stoplightio/elements, pull requests merged in 2021-11, with the labels that each got.

#1850 chore: remove lodash/fp methods
  packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
  packages/elements-dev-portal/src/components/Search/Search.tsx
  packages/elements-dev-portal/src/containers/StoplightProject.tsx
  packages/elements-utils/src/toc/toc.ts
  packages/elements/src/containers/API.spec.tsx
  packages/elements/src/containers/API.tsx
Labels: team/pierogi-platoon

#1851 chore(deps): bump mosaic from 1.8.2 to 1.12.4
  packages/elements-core/package.json
  packages/elements-dev-portal/package.json
  packages/elements/package.json
  yarn.lock
Labels: dependencies

#1853 chore: release elements
  packages/elements-core/package.json
  packages/elements-dev-portal/package.json
  packages/elements-utils/package.json
  packages/elements/package.json
Labels: team/pierogi-platoon

#1893 chore(core): do not log example generation failures
  packages/elements-core/src/utils/exampleGeneration/exampleGeneration.ts
Labels: chore
